### ISSUE TITLE
RFC: Preference object structure

### ISSUE THREAD

**Issue by joelrivera14** [jahorwitz/slopopedia#14]
Summary
This RFC proposes the structure of the "Preference" object to be stored in the database. It allows for a user to have a personalized SLOP experience.

Proposed Structure:
      name(string): name of user
      id(UUID): Unique movie ID or user ID // not sure
      category(string): name of category

Data Constraints:
Name: Must be unique.

Open Questions

i figured since all the preference data is based off a specific user, all that data is based of that ID. but then again im not sure, thoughts?

**Comment by colburncodes** [comment]
I believe there will be an additional table created between the user and preference table. UserPreference which will be a join table between the two. 

`UserPreference table (id, user_id, preference_id, preference_value)`

![Screen Shot 2023-09-04 at 11 04 22 AM](https://github.com/jahorwitz/slopopedia/assets/71975541/618f2950-a2ab-437f-b59e-d90db726e310)

Name field would be the values under People category. There is a list of data to populate into the table you are creating. I sent it to @jahorwitz I will also share with you @joelrivera14
