### ISSUE TITLE
RFC: This should outline the structure of the User Object in the database

### ISSUE THREAD

**Issue by colburncodes** [jahorwitz/slopopedia#2]
RFC: User Object Structure in the Database
Author: Colburn Sanders
Date: 8/10/2023

[Notion - DB Design](https://www.notion.so/coding-bootcamps/Info-for-students-1787069adb1f40f1b120c197db87d8cf)

[Figma - SLOP](https://www.figma.com/file/NDxE2DhULzua1KRFG6d4hA/Slopopedia?type=design&node-id=242-3965&mode=design&t=hscjoUHbVGpbbYte-0)

### Summary
This RFC outlines the proposed structure of the "User" object that will be stored in the database. The structure includes the essential attributes and their data types, which are necessary to support user-related functionality within the application.

### Motivation
Users are fundamental entities in our application, and defining a clear structure for the "User" object in the database is crucial to maintain consistency and efficiency in data storage and retrieval. This RFC aims to establish a standardized structure that can accommodate present and future requirements.

### Proposed Structure
The "User" object in the database will have the following attributes: Any additional fields?

ID (UUID): A unique identifier for each user.
Name (String): The unique name chosen by the user during registration. (required)
Email Address (String): The email address associated with the user's account. (required)
Password Hash (String): A secure hash of the user's password for authentication. (required)
Creation Date (Timestamp): The timestamp when the user account was created.
Last Login Date (Timestamp): The timestamp of the user's last login.
Profile Image URL (String): URL to the user's profile picture (optional).
Role (Enum): User role, such as 'admin' or 'user'.
Status (Enum): User status, such as 'active,' 'suspended,' or 'inactive.'
IsPrivileged (Boolean): User has the ability to edit. 
Green (Integer): Green threshold allows the user to see what kinds of scores movies end up with once their preferences are set and choose a lowest score for the movie to receive the green tag on the movie details page/popup.
Posts (Relationship): User can author many post.
Wishlist (Relationship): User can add many movies to their wishlist.
Watched (Relationship): User has watched many movies.
Preference (Relationship): User can personalize their slop experience.

### Data Constraints
What are our additional data constraints? We have the db design as a reference.

### Additional Considerations
Localization: Account for possible localization needs in attributes like user "token".
Security: Ensure sensitive attributes like "Password Hash" are properly secured.
Validation: Implement robust data validation to prevent data integrity issues.
Indexing: Consider indexing frequently queried attributes for faster retrieval.

### Open Questions
Should we store the user's date of birth for age-restricted content?
How should we handle password reset functionality considering the password hash?

**Comment by skwisgaarr8-9** [comment]
I think the proposed structure is good; I can't think of anything else to add at the moment. I don't think we need to store the user's DOB. We may want to ask Becca and Emily if they want to include age restrictions before we collect DOB information on every user. 

After a bit of research, it looks like we can do password resetting using a library like [Nodemailer](https://nodemailer.com/about/) to send emails with links that contain tokens (from jsonwebtoken) and reroute the user to a special route where we allow them to reset their password if the token in the sent URL matches the token we sent. [This link](https://www.geeksforgeeks.org/email-verification/) is about email verification but I think we can tweak it to be used for password reset.

**Comment by colburncodes** [comment]
I believe for password reset we can also consider using Keystone [Admin UI - Password Reset](https://keystonejs.com/docs/config/auth#password-reset-link) 

This option adds support for sending password reset links to users. The mutation sendUserPasswordResetLink allows you to send a reset token to a user.

**Comment by skwisgaarr8-9** [comment]
I was looking at that last night also but I was under the impression this is only for the Admin UI page. Do you think we can use these features in the broader application?

**Comment by colburncodes** [comment]
I believe so for the sake of this application since our backend is keystonejs. I think the idea is that keystonejs will give us the control to determine user session based off the flag isAdmin and isUser flag for Admin UI. We can use [GraphQL API](https://keystonejs.com/docs/config/auth#password-reset-graphql-api) for passwordResetLink. But I think you are right about Admin UI definitely to consider both scenarios.

**Comment by skwisgaarr8-9** [comment]
Okay I will try to look more into it tomorrow. If we can use that for all user password resets, that would be great. Otherwise we will have to incorporate another library that can send emails for us.

**Comment by colburncodes** [comment]
I completely agree!

**Comment by SamPage4427** [comment]
I think the structure is good. Is there a specific way we would assign a role to a user? We obviously should assign Becca as an admin, but are we planning to assign anyone who signs up to be a user and Becca has the ability to make them an admin? Also is isPrivileged only allowed for the posts that user creates and how would that work for fests?

**Comment by colburncodes** [comment]
Great questions. By default everyone who signs up would be a user. I added a role bc its a pretty standard approach with role a user has certain job functions and permissions to perform certain operations. IsPrivileged was originally EditPrivilege as part of the db design provided. So, I'm guessing a Admin user has the ability to determine who has privilege to edit.
