### ISSUE TITLE
RFC: This should outline the structure of the Post Object in the database 

### ISSUE THREAD

**Issue by colburncodes** [jahorwitz/slopopedia#6]
RFC: Post Object Structure in the Database
Author: Colburn Sanders
Date: 8/18/2023

[Notion - DB Design](https://www.notion.so/coding-bootcamps/Info-for-students-1787069adb1f40f1b120c197db87d8cf)

[Figma - SLOP](https://www.figma.com/file/NDxE2DhULzua1KRFG6d4hA/Slopopedia?type=design&node-id=242-3965&mode=design&t=hscjoUHbVGpbbYte-0)

Summary
This RFC outlines the proposed structure of the "Post" object that will be stored in the database. The structure includes the essential attributes and their data types, which are necessary to support post-related functionality within the application as a User.

Motivation
Posts are fundamental entities in our application, and defining a clear structure for the "Post" object in the database is crucial to maintain consistency and efficiency in data storage and retrieval. This RFC aims to establish a standardized structure that can accommodate present and future requirements.

Proposed Structure
The "Post" object in the database will have the following attributes: Any additional fields?

ID (UUID): A unique identifier for each post.
Title (String): The title will be created during post creation. (required)
Content (String): Document field used for creating rich content. (required)
Author (Relationship): User as the author of the post.
Creation Date (Timestamp): The timestamp when the post was created.
Status (Enum): Post status, such as 'draft' or 'published'.
Keywords (Relationship): Post can have many keywords associated. (optional?)
Slops (Relationship): Post can have many slop's associated. (optional?)

Suggestions
Should we have fields I have highlighted required?
Should we also consider having the ability as a user to add an image(s) to a post?

**Comment by skwisgaarr8-9** [comment]
I think that `Content` should be required. That is the meat of the post so without content we don't really have anything except a title and keywords which seems like a waste of database space to me. 

On `Images`, I can think that we should include it somehow. I am not exactly sure how it would work but user's may want to post memes or gifs in place of text content or in addition to text content in their posts.

**Comment by colburncodes** [comment]
[Digital Ocean Storage](https://docs.digitalocean.com/products/storage/)

[AWS S3 Bucket](https://aws.amazon.com/s3/)

Leaving this here for tracking
