### ISSUE TITLE
RFC: Movie Object Structure in the Database

### ISSUE THREAD

**Issue by Michaeljaurigue** [jahorwitz/slopopedia#7]
RFC: Movie Object Structure in the Database
Author: Michael Jaurigue
Date: 8/21/2023

**Summary**
This RFC proposes the structure of the "Movie" object to be stored in the database. It details essential attributes and their respective data types, designed to cater to the movie-related features of the application.

**Motivation**
Movies form a core aspect of our application, and a well-structured database model is crucial for maintaining data consistency, ensuring efficient storage and retrieval, and facilitating a seamless user experience. This RFC seeks to define a standardized structure that aligns with the application's current and anticipated features.

**Proposed Structure**
The "Movie" object in the database will comprise the following attributes:

ID (UUID): Unique identifier for each movie.
Title (String): The official name/title of the movie. (required)
Description (String): Brief summary or synopsis of the movie. (required)
RuntimeInMinutes (Number): The duration of the movie in minutes. (required)
RottenTomatoesScore (Number): The Rotten Tomatoes rating score as a percentage. (optional)
ReleaseYear (Number): The year the movie was released.
Image (String): URL pointing to the movie's poster or primary image. (optional)
HowToWatch (String): Information on platforms or services where the movie can be viewed. (required)
Keywords (Array of Strings): Tags or keywords associated with the movie.

**Data Constraints**
Referring to our database design:

Title: Must be unique.
RuntimeInMinutes: Positive integer.
RottenTomatoesScore: Between 0 to 100 (inclusive).
ReleaseYear: Should not be in the future.
Image: Must be a valid URL (if provided).
Additional Considerations

Localization: Consider potential needs for localization, especially for movie descriptions or titles in multiple languages.
Validation: Robust data validation is crucial, ensuring data consistency and preventing potential errors during storage or retrieval.
Indexing: Given movies might be frequently searched or filtered, indexing fields like "Title" or "ReleaseYear" can enhance retrieval speeds.

**Open Questions**

Should we incorporate user ratings or reviews directly into the Movie object?
How would we handle updates or changes in movie details, especially if sourced from third-party APIs or platforms?

**Comment by Michaeljaurigue** [comment]
![slopopedia movie upload](https://github.com/jahorwitz/slopopedia/assets/112568096/b090483d-e21b-48e0-a8ff-7821d5dac270)

This schema is based on the form at slopgoblins found at this link, https://slopgoblins.bubbleapps.io/

**Comment by colburncodes** [comment]
I think we should also consider the relationship between the User and Movie for database integrity. 
To illustrate:
`
author: relationship({ ref: "User.movie", many: true });
`

**Comment by skwisgaarr8-9** [comment]
I'm not sure how much we want to rely on their previous database design but this is what it looks like: 
<img width="278" alt="image" src="https://github.com/jahorwitz/slopopedia/assets/84792249/fc84594d-3fb5-4721-92da-4232dc702fcd">
You have got most of it but any idea what `Handicap` is referring to? 
`HowToWatch` is a nice idea. I wonder if it would be better as an array though to allow for multiple options?

**Comment by BrittneyAlfieri** [comment]
Adding the `HowToWatch` I think is a great idea. They don't leave it as a dropdown but as an open field to type. So I'm assuming it would autofill based off of a few letters on the potential options? Is there a list of specific potential options  that they would want user's to pick from for the HowToWatch category?

**Comment by SamPage4427** [comment]
Are we going to be making this a modal like they originally have it or are we going to make it a full page? The figma design has it as a full page but I think it would look better as a modal.

**Comment by Michaeljaurigue** [comment]
Thanks for all the comments! I'm about to push the changes to git hub now.
